# In interview-flow-dev/docker-compose.yml

services:
  interview_service:
    build:
      context: ./services/interview_services
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./services/interview_services:/code/interview_services
    command: uvicorn interview_services.app.main:app --host 0.0.0.0 --port 8000 --reload

