# In interview-flow-dev/docker-compose.yml

services:
  api_service:
    build:
      context: .
      dockerfile: services/api_service/Dockerfile
    environment:
      PYTHONPATH: /code/services
    ports:
      - "8003:8000"
    volumes:
      - .:/code
    command: uvicorn api_service.app.main:app --host 0.0.0.0 --port 8000 --reload
