# In interview-flow-dev/docker-compose.yml

services:
  ai_orchestration_service:
    build:
      context: ./services/ai_orchestration_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./services/ai_orchestration_service:/code/ai_orchestration_service
    command: uvicorn ai_orchestration_service.app.main:app --host 0.0.0.0 --port 8000 --reload
